job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()}")
    scm {
        git("https://github.com/karthikawstrainer/Jenkins-Maven.git", 'master')
    }
    triggers {
        scm('* * * * *')
    }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        //archive the war file generated
        archiveArtifacts '**/*.jar'
    }
}
